runpod_comfyui:
  base_path: /workspace/comfyui
  checkpoints: models/checkpoints/
  clip: models/clip/
  clip_vision: models/clip_vision/
  configs: models/configs/
  controlnet: models/controlnet/
  embeddings: models/embeddings/
  loras: models/loras/
  upscale_models: models/upscale_models/
  vae: models/vae/
  unet: models/unet/
  text_encoders: models/text_encoders/
  diffusion_models: models/diffusion_models/
  text_to_video: models/text_to_video/
  image_to_video: models/image_to_video/
  style_models: models/style_models/