name: Docker Build and Push (Multi-stage)

on:
  schedule:
    # Exécute le workflow tous les jours à 08:00 UTC
    - cron: "0 08 * * *"
  # Permet l'exécution manuelle depuis l'interface GitHub
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.multistage
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/comfyui_manager:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/comfyui_manager:${{ steps.date.outputs.DATE }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/comfyui_manager:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/comfyui_manager:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
